# Generated by Django 5.2.7 on 2025-10-25 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='documento',
        ),
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF (11 dígitos) ou CNPJ (14 dígitos)', max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Informe um CPF (11 dígitos) ou CNPJ (14 dígitos) válido.', regex='^\\d{11}|\\d{14}$')]),
        ),
    ]
