# Generated by Django 5.2.7 on 2025-11-27 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_empresa_documento_user_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='avaliacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta',
            field=models.IntegerField(default=0),
        ),
    ]
