# Generated by Django 5.2.7 on 2025-11-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_empresa_avaliacao_empresa_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='meta',
            field=models.IntegerField(default=1000),
        ),
    ]
