# Generated by Django 5.2.7 on 2025-11-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('users', '0002_remove_empresa_documento_user_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa'),
        ),
    ]
