# Generated by Django 5.2.7 on 2025-11-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_empresa'),
        ('users', '0002_remove_empresa_documento_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.empresa'),
            preserve_default=False,
        ),
    ]
