# Generated by Django 5.2.7 on 2025-11-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
