# Generated by Django 5.2.7 on 2025-11-26 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_empresa_documento_user_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_dinheiro', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('saldo_moeda', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to='users.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_ativo', models.CharField(choices=[('BRL', 'Dinheiro Real (R$)'), ('COIN', 'Moeda do App')], max_length=4)),
                ('tipo_operacao', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('COMPRA_COIN', 'Compra de Moeda'), ('GASTO', 'Gasto de Moeda/Serviço'), ('BONUS', 'Bônus/Recompensa'), ('SAQUE', 'Saque'), ('ESTORNO', 'Estorno')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_movimentado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='moeda.carteira')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['carteira', '-created_at'], name='moeda_trans_carteir_d08139_idx')],
            },
        ),
    ]
