# Generated by Django 4.2.7 on 2025-11-26 18:00

from django.db import migrations

def create_missing_wallets(apps, schema_editor):
    """
    Cria uma Carteira para cada Empresa que ainda não possui uma.
    """
    Empresa = apps.get_model('users', 'Empresa')
    Carteira = apps.get_model('moeda', 'Carteira')
    
    empresas_sem_carteira = Empresa.objects.filter(carteira__isnull=True)
    
    for empresa in empresas_sem_carteira:
        Carteira.objects.create(empresa=empresa)

def remove_wallets(apps, schema_editor):
    """
    Função reversa. Pode ser um no-op se a remoção não for desejada.
    Aqui, por segurança, não fazemos nada para não apagar dados.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0001_initial'),
        ('users', '0001_initial'), # Adicionar dependência do app users
    ]

    operations = [
        migrations.RunPython(create_missing_wallets, reverse_code=remove_wallets),
    ]
